### ISSUE TITLE
omnisharp--json-read-from-string error: "emacs: /usr/bin/curl: Argument list too long

### ISSUE THREAD

**Issue by taliszhou** [OmniSharp/omnisharp-emacs#193] opened 2015-08-15 18:37 UTC
hi,

i do gotodefinition, it log:
(:command "curl" :arguments ("--ipv4" "--silent" "-H" "Content-type: application/json" "--data" "{\"FileName\":"\babababababab.cs\",...........................................",  "http://localhost:2000/gotodefinition")}

omnisharp--json-read-from-string error: "emacs: /usr/bin/curl: Argument list too long

my work space:
ubuntu + emacs + mono (omnisharp-server)

**Comment by sp3ctum** [comment] 2015-08-15 18:41
How large is your file? Can you reproduce with a short file?
15.8.2015 9.37 ip. "taliszhou" <notifications@github.com> kirjoitti:

**Comment by taliszhou** [comment] 2015-08-15 19:01
i find a small file , and gotodefinition, log:

2015-08-16T02:58:58+0800
(:command "curl" :arguments ("--ipv4" "--silent" "-H" "Content-type: application/json" "--data" "null" "http://localhost:2000/checkalivestatus"))



2015-08-16T02:58:58+0800
omnisharp--json-read-from-string error: ""



2015-08-16T02:59:07+0800
(:command "curl" :arguments ("--ipv4" "--silent" "-H" "Content-type: application/json" "--data" "{\"FileName\":\"\\/home\\/android\\/Projects\\/fpa\\/fpa_website\\/NewHaoba.Hprose\\/Client\\/Ar$



2015-08-16T02:59:07+0800
omnisharp--json-read-from-string error: ""

**Comment by taliszhou** [comment] 2015-08-15 19:02
Thanks for the quick reply!

**Comment by taliszhou** [comment] 2015-08-15 19:04
my project has another clone working on windows,  the same using emacs+omnisharp,  it work fine.

**Comment by sp3ctum** [comment] 2015-08-15 19:06
Is the server running? Looks like `getalivestatus` receives no valid
response. Could you start the server with "-v Verbose" ? That will make it
log all requests and responses.

Are you using OmniSharp-server or omnisharp-roslyn?
15.8.2015 10.02 ip. "taliszhou" <notifications@github.com> kirjoitti:

**Comment by taliszhou** [comment] 2015-08-15 19:18
![1](https://cloud.githubusercontent.com/assets/3896399/9290421/6e9e94aa-43c5-11e5-9673-26d11ecba111.png)
![2](https://cloud.githubusercontent.com/assets/3896399/9290423/6ea216de-43c5-11e5-9d3d-557c4ce78bdb.png)
![3](https://cloud.githubusercontent.com/assets/3896399/9290422/6ea21170-43c5-11e5-85d5-96518a968b24.png)

**Comment by taliszhou** [comment] 2015-08-15 19:20
i using OmniSharp-server

**Comment by taliszhou** [comment] 2015-08-15 19:48
How to test it is working?

![4](https://cloud.githubusercontent.com/assets/3896399/9290520/7d19244c-43c9-11e5-8c40-240ae2959846.png)

**Comment by sp3ctum** [comment] 2015-08-15 19:52
Okay, it's good you're using the old server. It has better support and more features.

But instead of having omnisharp-server start in emacs, start it from the command line.

`mono OmniSharp.exe -s /path/to/solution/ -v Verbose`

This is the very same thing emacs does, and it allows you to spy on what the server sees. It effectively separates the server from emacs, allowing you to shut down emacs and start it again at will, if you need to.

So start the server like that, and then inspect what kinds of requests arrive. Try an `omnisharp-get-alive-status` or ready-status, and if they return `true`, paste back here the server's messages.

**Comment by sp3ctum** [comment] 2015-08-15 19:53
Doing `curl http://127.0.0.1:2000/checkalivestatus` will not work. That does an HTTP GET request, and the server only answers to POST requests.

**Comment by razzmatazz** [comment] 2017-07-23 04:58
@taliszhou  sorry for writing this late, but have you resolve the problem already?

we have a new version of omnisharp-emacs released that does not require curl anymore and has `omnisharp-install-server` command.

I am closing this issue because this issue is rather old, please reopen if this is still a problem for you.

**Closed by razzmatazz** 2017-07-23 04:58 UTC
Labels: non-roslyn, platform-unix
