### ISSUE TITLE
When MsBuildPath is specified in Server and has spaces in Path it fails

### ISSUE THREAD

**Issue by tbohnen** [OmniSharp/omnisharp-emacs#204] opened 2015-11-27 06:52 UTC
I've specified a custom build path in my config.json path to work with msbulid 14 (see below). That all works well but when Omnisharp tries to compile it it throws an error because there is a space in my path that is returned from the server. 

I've tested by changing it on the server side to include the quotation marks (as a hack to see if it works, which it does) but it almost feels like this should more be a change on the emacs side and that's why I'm submitting the issue here. If this is an issue, 

I would love to be able to implement a pull request for this if everyone agree that the right thing to do would be to surround the build path with quotation marks (at least in windows)?

"MsBuildPath" : "C:\Program Files (x86)\MSBuild\14.0\bin"
The build output with error is:

-_\- mode: compilation; default-directory: "~/Documents/Visual Studio 2015/Projects/CSharp 6 Features/CSharp 6 Features/" -_-
Compilation started at Fri Nov 27 08:50:14

C:/Program Files (x86)/MSBuild/14.0/bin/Msbuild.exe /m /nologo /v:q /property:GenerateFullPaths=true "c:/[PathToSolution]/ProjectName.csproj"
**'C:/Program' is not recognized as an internal or external command,
operable program or batch file.**

Compilation exited abnormally with code 1 at Fri Nov 27 08:50:14

My Setup: WIndows 7, Spacemacs version 0.104.3

**Comment by vincelee888** [comment] 2016-03-06 23:33
+1

**Comment by razzmatazz** [comment] 2017-07-23 05:03
@tbohnen @vincelee888 — is this still a problem for you with the new roslyn release (on melpa already)

also, I could not understand the problem right—how do you get this error? by compiling omnisharp server itself or some project with a command from a omnisharp-emacs buffer?

**Comment by razzmatazz** [comment] 2017-08-13 20:44
closing as the issue is referring to the old omnisharp server/client.
please reopen if still relevant

**Closed by razzmatazz** 2017-08-13 20:44 UTC
Labels: non-roslyn, platform-windows, spacemacs
