### ISSUE TITLE
feature-omnisharp-rosalyn-support branch crashes Windows emacs 24.5.1 when starting server

### ISSUE THREAD

**Issue by sbroberg** [OmniSharp/omnisharp-emacs#260] opened 2016-11-11 13:59 UTC
I'm trying to get a basic configuration working with the rosalyn server.  When I run `omnisharp-start-omnisharp-server` from the directory containing my .sln file, emacs crashes.

I'm running the native emacs 24.5.1, using the current feature-omnisharp-rosalyn-support branch, along with the current dev branch of omnisharp-roslyn.

My init.el:

```
;; Melpa
(require 'package)
(add-to-list 'package-archives
	     '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.milkbox.net/packages/") t)

(package-initialize)
;; END Melpa

(require 'company)
(require 'csharp-mode)
(add-to-list 'load-path (expand-file-name "~/omnisharp-emacs"))
(load "omnisharp.el")
(add-hook 'csharp-mode-hook 'omnisharp-mode)

(setq omnisharp-server-executable-path "c:\\Users\\developer\\omnisharp-roslyn\\artifacts\\publish\\OmniSharp\\default\\net451\\OmniSharp.exe")
(setq omnisharp-debug t)

```

The output from the server, if I start it from the command line, with the arguments I'd expect to be passed when launched from emacs:

```
C:\Users\developer\omnisharp-roslyn\artifacts\publish\OmniSharp\default\net451>OmniSharp.exe -v -s "C:\Users\developer\Desktop\CSharp Console App"
OmniSharp: -v -s C:\Users\developer\Desktop\CSharp Console App
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.DotNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.DotNetTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Nuget, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Roslyn.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.ScriptCs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Stdio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location 'C:\Users\developer\Desktop\CSharp Console App' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in C:\Users\developer\Desktop\CSharp Console App
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp#MSBuild[0]
      Detecting projects in 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App.sln'.
info: OmniSharp#MSBuild[0]
      Loading project from 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
info: OmniSharp#ProjectFileInfo[0]
      Using toolset 2.0 for C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll' to 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll' to 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll' to 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll' to 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll' to 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll' to 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll' to 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll' to 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
info: OmniSharp.ScriptCs.ScriptCsProjectSystem[0]
      Detecting CSX files in 'C:\Users\developer\Desktop\CSharp Console App'.
info: OmniSharp.ScriptCs.ScriptCsProjectSystem[0]
      Could not find any CSX files
info: OmniSharp.Startup[0]
      Configuration finished.
dbug: OmniSharp.DotNet.DotNetProjectSystem[0]
      GetProjectModel C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj
dbug: OmniSharp.DotNet.DotNetProjectSystem[0]
      GetProjectModel C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj



```

**Comment by jtbm37** [comment] 2016-11-11 22:55
I can also confirm this happens on Windows, but not on Linux.

**Comment by jtbm37** [comment] 2016-11-11 23:29
If you are looking for a quick workaround, use the http mode.
1) Install package `request-deferred`
2) Add this to your init.el `(setq omnisharp-use-http t)`
3) Start the server from the command-line
4) Open your cs file and start coding.

If you want to get auto-completion working you'll have to add a backend for omnisharp like so
``` lisp
(defun my-omnisharp-mode-hook ()
  (setq-local company-backends '(company-omnisharp company-dabbrev-code company-keywords))
  (company-mode))
(add-hook 'omnisharp-mode-hook 'my-omnisharp-mode-hook)

```

**Comment by jtbm37** [comment] 2016-11-11 23:32
Use my [config](https://github.com/jtbm37/dotfiles/blob/master/emacs/private/my-omnisharp.el) if in doubt.

**Comment by razzmatazz** [comment] 2017-07-17 08:13
@sbroberg @jtbm37 sorry for replying this late, but I think I found the cause for the crash:
 - .NET binaries compiled for x64 are crashing emacs host on Windows, see #315

the solution is to use x86 roslyn binary OR (preferrably) use the new `M-x omnisharp-install-server` command which should download and set up the server for you. (you need to comment out `(setq omnisharp-server-executable-path)` in your init.el)

curl should be used as a last resort, I think..

**Comment by razzmatazz** [comment] 2017-07-23 05:24
I am closing this as the crash should be gone with x86 server on windows (or with `M-x omnisharp-install-server`). Please reopen if this is still valid.

**Closed by razzmatazz** 2017-07-23 05:24 UTC
Labels: bug, platform-windows
